// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5H-fo0TJiBGQxt0UaxdHQN12QtxjyAMw',
    appId: '1:608237436557:web:fac77f64fc15b105136cc4',
    messagingSenderId: '608237436557',
    projectId: 'fragments-a203e',
    authDomain: 'fragments-a203e.firebaseapp.com',
    storageBucket: 'fragments-a203e.appspot.com',
    measurementId: 'G-027EYKJR2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3xin-Isx0cB2ElzUNRVZ_gGXjWAqszo',
    appId: '1:608237436557:android:54330a7e08a46d3c136cc4',
    messagingSenderId: '608237436557',
    projectId: 'fragments-a203e',
    storageBucket: 'fragments-a203e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9LB6Qofy9CwtAXAu8JwlrEtRoZtk1Y7Y',
    appId: '1:608237436557:ios:f1b3bd45226f494e136cc4',
    messagingSenderId: '608237436557',
    projectId: 'fragments-a203e',
    storageBucket: 'fragments-a203e.appspot.com',
    iosClientId: '608237436557-b1ppvnhasseu2mhn4jjkchd4b1549bj1.apps.googleusercontent.com',
    iosBundleId: 'com.mahitm.fragments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9LB6Qofy9CwtAXAu8JwlrEtRoZtk1Y7Y',
    appId: '1:608237436557:ios:e5bcb95022839db4136cc4',
    messagingSenderId: '608237436557',
    projectId: 'fragments-a203e',
    storageBucket: 'fragments-a203e.appspot.com',
    iosClientId: '608237436557-dtme90i7poms7832acud7jud2h4qcofq.apps.googleusercontent.com',
    iosBundleId: 'com.mahitm.fragments.RunnerTests',
  );
}
